REALM667W = { }

REALM667W.WEAPONS =
{	
	GrenadeLauncher40mm =
	{
		id = 29010,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	AA12 =
	{
		id = 29604,
		level = 8,
		pref = 2,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "shell",
		per = 1,
	},
	ActionMachineGun =
	{
		id = 29124,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	AK47 =
	{
		id = 29125,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	AlphaUnmaker =
	{
		id = 29263,
		level = 8,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	--disabled by default
	AngledPistol =
	{
		id = 29128,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Autogun =
	{
		id = 29130,
		level = 6,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	AutoShot =
	{
		id = 5664,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "shell",
		per = 1,
	},
	--disabled by default
	Axe =
	{
		id = 29131,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	--disabled by default
	BayonetRifle =
	{
		id = 29132,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	BFG2704 =
	{
		id = 29140,
		level = 7,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	BHGen =
	{
		id = 29150,
		level = 6,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	BioPipebombLauncher =
	{
		id = 29141,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Bolter =
    {
	    id = 17376,
		level = 8,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	--BratwurstWeapons.wad start
	--WolfKnife disabled by default
	WolfKnife =
    {
	    id = 17446,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "melee",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	WolfPistol =
    {
	    id = 17440,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "melee",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	WolfMachineGun =
    {
	    id = 17441,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "melee",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	WolfGatlingGun =
    {
	    id = 17442,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "melee",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	--BratwurstWeapons.wad end
	BRPS =
	{
		id = 17363,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	Butchergun =
	{
		id = 29151,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Channeler =
	{
		id = 29152,
		level = 7,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	--disabled by default
	ClaymoreMine =
	{
		id = 10200,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Coachgun =
	{
		id = 29160,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Colt45 =
	{
		id = 5757,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	CryoBow =
	{
		id = 29161,
		level = 9,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	--disabled by default
	D2C_Pipebomb =
	{
		id = 25018,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	DemonicLeech =
	{
		id = 29170,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	DesertEagle =
	{
		id = 425,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	DGL =
	{
		id = 29173,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Doom3SSG =
	{
		id = 29171,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "shell",
		per = 1	
	},
	DoubleBladedChainsaw =
	{
		id = 29172,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	DualLaser =
	{
		id = 5666,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	DukePistol =
	{
		id = 17392,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	DukeShotgun =
	{
		id = 29174,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "shell",
		per = 1,
	},
	EgoSmasher =
	{
		id = 29175,
		level = 10,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	ElectroGun =
	{
		id = 29176,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	EMSRifle =
	{
		id = 29177,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	--disabled by default
	FistRedux =
	{
		id = 29178,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	FistsOfFury =
	{
		id = 17384,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	FlakCannon =
	{
		id = 2052,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "shell",
		per = 1,
	},
	-- disabled by default
	FlashLightAngled =
	{
		id = 29182,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	-- disabled by default
	FragGrenade =
	{
		id = 11907,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	FreezeRifle =
	{
		id = 29183,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	GasGun =
	{
		id = 20039,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	GatLaser =
	{
		id = 6570,
		level = 6,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	Glock18 =
	{
		id = 29184,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	--disabled by default
	HandGrenade =
	{
		id = 25099,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	--disabled by default
	HeavyCarbine =
	{
		id = 20212,
		level = 5,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	HeavyChaingun =
	{
		id = 29605,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	HeavyMachineGun =
	{
		id = 602,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	HeavyRifle =
	{
		id = 25035,
		level = 10,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	HellstormCannon =
	{
		id = 29187,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	HuntingRifle =
	{
		id = 29190,
		level = 7,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	iGun =
	{
		id = 29191,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Ionspray =
	{
		id = 29192,
		level = 6,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Karasawa =
	{
		id = 29193,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	KDiZDGrenadeLauncher =
	{
		id = 29186,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	KDiZDSuperShotgun =
	{
		id = 29257,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	-- disabled by default
	Knife =
	{
		id = 29194,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	-- disabled by default
	LandMineLayer =
	{
		id = 29195,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	LaserCannon =
	{
		id = 29197,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	LightMachinegun =
	{
		id = 601,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	M16 =
	{
		id = 29198,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	M40Rifle =
	{
		id = 29199,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	M79 =
	{
		id = 29202,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	--disabled by default
	Machete =
	{
		id = 29205,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Machinegun =
	{
		id = 29206,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Mag60 =
	{
		id = 5509,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	MancubusArm =
	{
		id = 29207,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	DualMancubusArm =
	{
		id = 29208,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	MicroUzi =
	{
		id = 29606,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	model1887 =
	{
		id = 29210,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	--disabled by default
	MP40 =
	{
		id = 12400,
		level = 2,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	MP5 =
	{
		id = 29211,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	NailGunMG =
	{
		id = 29212,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	NailgunSG =
	{
		id = 29214,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	NuclearMissileLauncher =
	{
		id = 29608,
		level = 10,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	PlasmaBallista =
	{
		id = 29217,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	PlasmaBeam =
	{
		id = 29218,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	PlasmaBolter =
	{
		id = 29219,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	PlasmaPistol =
	{
		id = 29220,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	PlasmaQuadShotgun =
	{
		id = 17388,
		level = 8,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	PlasmaRepeater =
	{
		id = 5012,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	PlasmaRocketLauncher =
	{
		id = 17389,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "missile",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	PlasmaShotgun =
	{
		id = 29221,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	PlasmaSplitter =
	{
		id = 17366,
		level = 6,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	PulseNailgun =
	{
		id = 29609,
		level = 3.5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	PulseRifle =
	{
		id = 18730,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	PumpActionShotgun =
	{
		id = 29227,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	QuadShotgun =
	{
		id = 29999,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Raptor =
	{
		id = 29230,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Raygun =
	{
		id = 12634,
		level = 9,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	Reaper =
	{
		id = 6021,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Repeater =
	{
		id = 29231,
		level = 8,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	--disabled by default
	Rifle =
	{
		id = 25096,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	RivetGun =
	{
		id = 7932,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	RocketLaunchermkII =
	{
		id = 17378,
		level = 10,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "missile",
		rate = 0.9,
		damage = 10,
		ammo = "rocket",
		per = 1,
	},
	Satcheler =
	{
		id = 29126,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	ScatterPistol =
	{
		id = 29238,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	--disabled by default
	ShieldGun =
	{
		id = 29239,
		level = 1,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	ShockRifle =
	{
		id = 17368,
		level = 3,
		pref = 5,
		add_prob = 0,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	SidebySide =
	{
		id = 29240,
		level = 7,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	SilencedPistol =
	{
		id = 29241,
		level = 1,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	SingleShot =
	{
		id = 29242,
		level = 1,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	SkeletalRevenge =
	{
		id = 29243,
		level = 6,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	SlugShotgun =
	{
		id = 17390,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Smartgun =
	{
		id = 29250,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Smasher =
	{
		id = 12465,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	SniperRifle =
	{
		id = 2395,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	SPAS12 =
	{
		id = 29251,
		level = 3,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	SprayCannon =
	{
		id = 29252,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	STBFG10K =
	{
		id = 29136,
		level = 8,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "cell",
		per = 1,
	},
	STGrenadeLauncher =
	{
		id = 29185,
		level = 6,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	STMinigun =
	{
		id = 29607,
		level = 6,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	STRailgun =
	{
		id = 29229,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	StrifePistol =
	{
		id = 29255,
		level = 1,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	StunnerRifle =
	{
		id = 29256,
		level = 10,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	SuperMiniMissileLauncher =
	{
		id = 17394,
		level = 6,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "missile",
		rate = 0.9,
		damage = 10,
		ammo = "rocket",
		per = 1,
	},
	SuppressedMP5 =
	{
		id = 29258,
		level = 4,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	SwatShotgun =
	{
		id = 29259,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "shell",
		per = 1,
	},
	TacticalShotgun =
	{
		id = 17367,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "shell",
		per = 1,
	},
	Thompson =
	{
		id = 29260,
		level = 8,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Toaster =
	{
		id = 12466,
		level = 10,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	UACPlasmaticRifle =
	{
		id = 29261,
		level = 7,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	UberMinigun =
	{
		id = 29262,
		level = 6,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	UTNTFlamethrower =
	{
		id = 29179,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	UTNTPyroCannon =
	{
		id = 29269,
		level = 7,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	Uzi =
	{
		id = 17459,
		level = 5,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "bullet",
		per = 1,
	},
	WensternShotgun =
	{
		id = 29272,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "shell",
		per = 1,
	},
	Yellowboy =
	{
		id = 22911,
		level = 2,
		pref = 5,
		add_prob = 1,
		hide_prob = 80,
		attack = "hitscan",
		rate = 0.9,
		damage = 10,
		ammo = "shell",
		per = 1,
	},
}


REALM667W.PICKUPS =
{
  Grenades40mm =
  {
    id = 5567,
    kind = "ammo",
    add_prob = 20,
    cluster = { 4,7 },
    give = { {ammo="40mmGrenades", count=5} },
  },
  Grenades40mmBox =
  {
    id = 5568,
	kind = "ammo",
	add_prob = 20,
	give = { {ammo="40mmGrenades", count=20 } },
  },
  BioContainer =
  {
    id = 29146,
    kind = "ammo",
    add_prob = 20,
    cluster = { 4,7 },
    give = { {ammo="BioContainer", count=6} },
  },
  BioContainerHefty =
  {
    id = 29147,
	kind = "ammo",
	add_prob = 20,
	give = { {ammo="BioContainer", count=30 } },
  },
  --Claymore goes here when I'm not feeling lazy
  
  --EMS Rifle = Slugs
  Slugs =
    {
    id = 5660,
    kind = "ammo",
    add_prob = 20,
    give = { {ammo="Slugs", count=12} },
   },
   SlugMag =
    {
    id = 5661,
    kind = "ammo",
    add_prob = 20,
    give = { {ammo="Slugs", count=6} },
  },
  FlakAmmo =
  {
    id = 2050,
    kind = "ammo",
    add_prob = 20,
    give = { {ammo="FlakAmmo", count=2} },
  },
    FlakAmmoBox =
  {
    id = 2051,
    kind = "ammo",
    add_prob = 20,
    give = { {ammo="FlakAmmo", count=6} },
  },
  
  --Hand Grenade goes here when I'm not feeling lazy
  
  --Karasawa goes here when I'm not feeling lazy
  
  --Landmine Layer
  
  NuclearMissile =
  {
   id = 29216,
    kind = "ammo",
    add_prob = 5,
    give = { {ammo="NuclearMissile", count=1} },
  },
  
   Rivets =
  {
    id = 32257,
    kind = "ammo",
    add_prob = 20,
    give = { {ammo="Rivets", count=12} },
  },
   RivetRack =
  {
    id = 32258,
    kind = "ammo",
    add_prob = 20,
    give = { {ammo="RivetRack", count=25} },
  },
  
  
  --Unmaker
  
  
}


-- Interface code below...

REALM667W.WEAPON_CHOICES =
{
  "default", _("DEFAULT"),
  "none",    _("None at all"),
  "scarce",  _("Scarce"),
  "less",    _("Less"),
  "plenty",  _("Plenty"),
  "more",    _("More"),
  "heaps",   _("Heaps"),
  "loveit",  _("I LOVE IT"),
}

REALM667W.WEAPON_PROBS =
{
  none   = 0,
  scarce = 2,
  less   = 15,
  plenty = 50,
  more   = 120,
  heaps  = 300,
  loveit = 1000,
}

REALM667W.WEAPON_PREFS =
{
  none   = 1,
  scarce = 10,
  less   = 25,
  plenty = 40,
  more   = 70,
  heaps  = 100,
  loveit = 170,
}


function REALM667W.weapon_setup(self)
  for name,opt in pairs(self.options) do
    local W = GAME.WEAPONS[name]

    if W and opt.value ~= "default" then
      W.add_prob = REALM667W.WEAPON_PROBS[opt.value]
      W.pref     = REALM667W.WEAPON_PREFS[opt.value]

      -- loosen some of the normal restrictions
      W.level = 1
    end
  end -- for opt
end





OB_MODULES["REALM667W"] =
{
  label = "Realm667 Weapons",

  game = "doomish",

  hooks =
  {
    setup = REALM667W.weapon_setup
  },

  tables =
  {
    REALM667W
  },

  options =
  {

GrenadeLauncher40mm     =  {  label=_("GrenadeLauncher40mm"),     choices=REALM667W.WEAPON_CHOICES  },
AA12                    =  {  label=_("AA12"),                    choices=REALM667W.WEAPON_CHOICES  },
ActionMachineGun        =  {  label=_("ActionMachineGun"),        choices=REALM667W.WEAPON_CHOICES  },
AK47                    =  {  label=_("AK47"),                    choices=REALM667W.WEAPON_CHOICES  },
AlphaUnmaker            =  {  label=_("AlphaUnmaker"),            choices=REALM667W.WEAPON_CHOICES  },
AngledPistol            =  {  label=_("AngledPistol"),            choices=REALM667W.WEAPON_CHOICES  },
Autogun                 =  {  label=_("Autogun"),                 choices=REALM667W.WEAPON_CHOICES  },
AutoShot                =  {  label=_("AutoShot"),                choices=REALM667W.WEAPON_CHOICES  },
Axe                     =  {  label=_("Axe"),                     choices=REALM667W.WEAPON_CHOICES  },
BayonetRifle            =  {  label=_("BayonetRifle"),            choices=REALM667W.WEAPON_CHOICES  },
BFG2704                 =  {  label=_("BFG2704"),                 choices=REALM667W.WEAPON_CHOICES  },
BHGen                   =  {  label=_("BHGen"),                   choices=REALM667W.WEAPON_CHOICES  },
BioPipebombLauncher     =  {  label=_("BioPipebombLauncher"),     choices=REALM667W.WEAPON_CHOICES  },
Bolter     =  {  label=_("Bolter"),     choices=REALM667W.WEAPON_CHOICES  },
--Bratwurst Weapons.wad
WolfKnife     =  {  label=_("WolfKnife"),     choices=REALM667W.WEAPON_CHOICES  },
WolfPistol     =  {  label=_("WolfPistol"),     choices=REALM667W.WEAPON_CHOICES  },
WolfMachineGun     =  {  label=_("WolfMachineGun"),     choices=REALM667W.WEAPON_CHOICES  },
WolfGatlingGun     =  {  label=_("WolfGatlingGun"),     choices=REALM667W.WEAPON_CHOICES  },
--End Bratwurst Weapons.wad
BRPS     =  {  label=_("BRPS"),     choices=REALM667W.WEAPON_CHOICES  },
Butchergun              =  {  label=_("Butchergun"),              choices=REALM667W.WEAPON_CHOICES  },
Channeler               =  {  label=_("Channeler"),               choices=REALM667W.WEAPON_CHOICES  },
ClaymoreMine            =  {  label=_("ClaymoreMine"),            choices=REALM667W.WEAPON_CHOICES  },
Coachgun                =  {  label=_("Coachgun"),                choices=REALM667W.WEAPON_CHOICES  },
Colt45                  =  {  label=_("Colt45"),                  choices=REALM667W.WEAPON_CHOICES  },
CryoBow                 =  {  label=_("CryoBow"),                 choices=REALM667W.WEAPON_CHOICES  },
D2C_Pipebomb            =  {  label=_("D2C_Pipebomb"),            choices=REALM667W.WEAPON_CHOICES  },
DemonicLeech            =  {  label=_("DemonicLeech"),            choices=REALM667W.WEAPON_CHOICES  },
DesertEagle            =  {  label=_("DesertEagle"),            choices=REALM667W.WEAPON_CHOICES  },
DGL                     =  {  label=_("DGL"),                     choices=REALM667W.WEAPON_CHOICES  },
Doom3SSG                     =  {  label=_("Doom3SSG"),                     choices=REALM667W.WEAPON_CHOICES  },
DoubleBladedChainsaw    =  {  label=_("DoubleBladedChainsaw"),    choices=REALM667W.WEAPON_CHOICES  },
DualLaser               =  {  label=_("DualLaser"),               choices=REALM667W.WEAPON_CHOICES  },
DukePistol             =  {  label=_("DukePistol"),             choices=REALM667W.WEAPON_CHOICES  },
DukeShotgun             =  {  label=_("DukeShotgun"),             choices=REALM667W.WEAPON_CHOICES  },
EgoSmasher              =  {  label=_("EgoSmasher"),              choices=REALM667W.WEAPON_CHOICES  },
ElectroGun              =  {  label=_("ElectroGun"),              choices=REALM667W.WEAPON_CHOICES  },
EMSRifle              =  {  label=_("EMSRifle"),              choices=REALM667W.WEAPON_CHOICES  },
FistRedux               =  {  label=_("FistRedux"),               choices=REALM667W.WEAPON_CHOICES  },
FistsOfFury               =  {  label=_("FistsOfFury"),               choices=REALM667W.WEAPON_CHOICES  },
FlakCannon               =  {  label=_("FlakCannon"),               choices=REALM667W.WEAPON_CHOICES  },
FlashLightAngled        =  {  label=_("FlashLightAngled"),        choices=REALM667W.WEAPON_CHOICES  },
FragGrenade             =  {  label=_("FragGrenade"),             choices=REALM667W.WEAPON_CHOICES  },
FreezeRifle             =  {  label=_("FreezeRifle"),             choices=REALM667W.WEAPON_CHOICES  },
GasGun                  =  {  label=_("GasGun"),                  choices=REALM667W.WEAPON_CHOICES  },
GatLaser                =  {  label=_("GatLaser"),                choices=REALM667W.WEAPON_CHOICES  },
Glock18                 =  {  label=_("Glock18"),                 choices=REALM667W.WEAPON_CHOICES  },
HandGrenade             =  {  label=_("HandGrenade"),             choices=REALM667W.WEAPON_CHOICES  },
HeavyCarbine            =  {  label=_("HeavyCarbine"),            choices=REALM667W.WEAPON_CHOICES  },
HeavyChaingun            =  {  label=_("HeavyChaingun"),            choices=REALM667W.WEAPON_CHOICES  },
HeavyMachinegun		= { label=_("HeavyMachineGun"),			choices=REALM667W.WEAPON_CHOICES  },
HeavyRifle              =  {  label=_("HeavyRifle"),              choices=REALM667W.WEAPON_CHOICES  },
HellstormCannon         =  {  label=_("HellstormCannon"),         choices=REALM667W.WEAPON_CHOICES  },
HuntingRifle         =  {  label=_("HuntingRifle"),         choices=REALM667W.WEAPON_CHOICES  },
iGun                    =  {  label=_("iGun"),                    choices=REALM667W.WEAPON_CHOICES  },
Ionspray                =  {  label=_("Ionspray"),                choices=REALM667W.WEAPON_CHOICES  },
Karasawa                =  {  label=_("Karasawa"),                choices=REALM667W.WEAPON_CHOICES  },
KDiZDGrenadeLauncher    =  {  label=_("KDiZDGrenadeLauncher"),    choices=REALM667W.WEAPON_CHOICES  },
KDiZDSuperShotgun       =  {  label=_("KDiZDSuperShotgun"),       choices=REALM667W.WEAPON_CHOICES  },
Knife                   =  {  label=_("Knife"),                   choices=REALM667W.WEAPON_CHOICES  },
LandMineLayer           =  {  label=_("LandMineLayer"),           choices=REALM667W.WEAPON_CHOICES  },
LaserCannon             =  {  label=_("LaserCannon"),             choices=REALM667W.WEAPON_CHOICES  },
LightMachinegun             =  {  label=_("LightMachinegun"),             choices=REALM667W.WEAPON_CHOICES  },
M16                     =  {  label=_("M16"),                     choices=REALM667W.WEAPON_CHOICES  },
M40Rifle                =  {  label=_("M40Rifle"),                choices=REALM667W.WEAPON_CHOICES  },
M79                     =  {  label=_("M79"),                     choices=REALM667W.WEAPON_CHOICES  },
Machete                 =  {  label=_("Machete"),                 choices=REALM667W.WEAPON_CHOICES  },
Machinegun              =  {  label=_("Machinegun"),              choices=REALM667W.WEAPON_CHOICES  },
Mag60                   =  {  label=_("Mag60"),                   choices=REALM667W.WEAPON_CHOICES  },
MancubusArm             =  {  label=_("MancubusArm"),             choices=REALM667W.WEAPON_CHOICES  },
DualMancubusArm             =  {  label=_("DualMancubusArm"),             choices=REALM667W.WEAPON_CHOICES  },
MicroUzi                =  {  label=_("MicroUzi"),                choices=REALM667W.WEAPON_CHOICES  },
model1887               =  {  label=_("model1887"),               choices=REALM667W.WEAPON_CHOICES  },
MP40                    =  {  label=_("MP40"),                    choices=REALM667W.WEAPON_CHOICES  },
MP5                     =  {  label=_("MP5"),                     choices=REALM667W.WEAPON_CHOICES  },
NailGunMG               =  {  label=_("NailGunMG"),               choices=REALM667W.WEAPON_CHOICES  },
NailgunSG               =  {  label=_("NailgunSG"),               choices=REALM667W.WEAPON_CHOICES  },
NuclearMissileLauncher  =  {  label=_("NuclearMissileLauncher"),  choices=REALM667W.WEAPON_CHOICES  },
PlasmaBallista          =  {  label=_("PlasmaBallista"),          choices=REALM667W.WEAPON_CHOICES  },
PlasmaBeam              =  {  label=_("PlasmaBeam"),              choices=REALM667W.WEAPON_CHOICES  },
PlasmaBolter            =  {  label=_("PlasmaBolter"),            choices=REALM667W.WEAPON_CHOICES  },
PlasmaPistol            =  {  label=_("PlasmaPistol"),            choices=REALM667W.WEAPON_CHOICES  },
PlasmaQuadShotgun            =  {  label=_("PlasmaQuadShotgun"),            choices=REALM667W.WEAPON_CHOICES  },
PlasmaRepeater          =  {  label=_("PlasmaRepeater"),          choices=REALM667W.WEAPON_CHOICES  },
PlasmaRocketLauncher          =  {  label=_("PlasmaRocketLauncher"),          choices=REALM667W.WEAPON_CHOICES  },
PlasmaShotgun           =  {  label=_("PlasmaShotgun"),           choices=REALM667W.WEAPON_CHOICES  },
PulseNailgun            =  {  label=_("PulseNailgun"),            choices=REALM667W.WEAPON_CHOICES  },
PulseRifle              =  {  label=_("PulseRifle"),              choices=REALM667W.WEAPON_CHOICES  },
PumpActionShotgun       =  {  label=_("PumpActionShotgun"),       choices=REALM667W.WEAPON_CHOICES  },
QuadShotgun             =  {  label=_("QuadShotgun"),             choices=REALM667W.WEAPON_CHOICES  },
Raptor                  =  {  label=_("Raptor"),                  choices=REALM667W.WEAPON_CHOICES  },
Raygun                  =  {  label=_("Raygun"),                  choices=REALM667W.WEAPON_CHOICES  },
Reaper                  =  {  label=_("Reaper"),                  choices=REALM667W.WEAPON_CHOICES  },
Repeater                =  {  label=_("Repeater"),                choices=REALM667W.WEAPON_CHOICES  },
Rifle                   =  {  label=_("Rifle"),                   choices=REALM667W.WEAPON_CHOICES  },
Rifle                   =  {  label=_("Rifle"),                   choices=REALM667W.WEAPON_CHOICES  },
RivetGun                =  {  label=_("RivetGun"),                choices=REALM667W.WEAPON_CHOICES  },
RocketLaunchermkII                =  {  label=_("RocketLaunchermkII"),                choices=REALM667W.WEAPON_CHOICES  },
Satcheler           =  {  label=_("Satcheler"),           choices=REALM667W.WEAPON_CHOICES  },
ScatterPistol           =  {  label=_("ScatterPistol"),           choices=REALM667W.WEAPON_CHOICES  },
ShieldGun               =  {  label=_("ShieldGun"),               choices=REALM667W.WEAPON_CHOICES  },
SidebySide              =  {  label=_("SidebySide"),              choices=REALM667W.WEAPON_CHOICES  },
SilencedPistol          =  {  label=_("SilencedPistol"),          choices=REALM667W.WEAPON_CHOICES  },
SingleShot              =  {  label=_("SingleShot"),              choices=REALM667W.WEAPON_CHOICES  },
SkeletalRevenge         =  {  label=_("SkeletalRevenge"),         choices=REALM667W.WEAPON_CHOICES  },
SlugShotgun         =  {  label=_("SlugShotgun"),         choices=REALM667W.WEAPON_CHOICES  },
Smartgun                =  {  label=_("Smartgun"),                choices=REALM667W.WEAPON_CHOICES  },
Smasher                 =  {  label=_("Smasher"),                 choices=REALM667W.WEAPON_CHOICES  },
SniperRifle             =  {  label=_("SniperRifle"),             choices=REALM667W.WEAPON_CHOICES  },
SPAS12                  =  {  label=_("SPAS12"),                  choices=REALM667W.WEAPON_CHOICES  },
SprayCannon             =  {  label=_("SprayCannon"),             choices=REALM667W.WEAPON_CHOICES  },
STBFG10K                =  {  label=_("STBFG10K"),                choices=REALM667W.WEAPON_CHOICES  },
STGrenadeLauncher       =  {  label=_("STGrenadeLauncher"),       choices=REALM667W.WEAPON_CHOICES  },
STMinigun               =  {  label=_("STMinigun"),               choices=REALM667W.WEAPON_CHOICES  },
STRailgun               =  {  label=_("STRailgun"),               choices=REALM667W.WEAPON_CHOICES  },
StrifePistol               =  {  label=_("StrifePistol"),               choices=REALM667W.WEAPON_CHOICES  },
StunnerRifle               =  {  label=_("StunnerRifle"),               choices=REALM667W.WEAPON_CHOICES  },
SuperMiniMissileLauncher           =  {  label=_("SuperMiniMissileLauncher"),           choices=REALM667W.WEAPON_CHOICES  },
SuppressedMP5           =  {  label=_("SuppressedMP5"),           choices=REALM667W.WEAPON_CHOICES  },
SwatShotgun             =  {  label=_("SwatShotgun"),             choices=REALM667W.WEAPON_CHOICES  },
Thompson                =  {  label=_("Thompson"),                choices=REALM667W.WEAPON_CHOICES  },
Toaster                 =  {  label=_("Toaster"),                 choices=REALM667W.WEAPON_CHOICES  },
UACPlasmaticRifle       =  {  label=_("UACPlasmaticRifle"),       choices=REALM667W.WEAPON_CHOICES  },
UberMinigun             =  {  label=_("UberMinigun"),             choices=REALM667W.WEAPON_CHOICES  },
UTNTFlamethrower        =  {  label=_("UTNTFlamethrower"),        choices=REALM667W.WEAPON_CHOICES  },
UTNTPyroCannon          =  {  label=_("UTNTPyroCannon"),          choices=REALM667W.WEAPON_CHOICES  },
Uzi                     =  {  label=_("Uzi"),                     choices=REALM667W.WEAPON_CHOICES  },
WensternShotgun         =  {  label=_("WensternShotgun"),         choices=REALM667W.WEAPON_CHOICES  },
Yellowboy               =  {  label=_("Yellowboy"),               choices=REALM667W.WEAPON_CHOICES  },

  },
}
